version: '2'

services:
  test:
    image: mcr.microsoft.com/dotnet/core/sdk:2.2
    depends_on: 
      - acquirer
    working_dir: /opt/workspace
    volumes:
      - ./:/opt/workspace
    command: bash -c "dotnet test --output tmp/build -c Release --logger trx"

  acquirer:
    image: jordimartin/mmock
    ports:
      - 8082:8082
      - 8083:8083
    environment:
      - LOG_LEVEL=INFO
      - jvmOptions=-Dmockserver.initializationJsonPath=/config/mock-acquirer-setup.json
    volumes:
      - ./config:/config