version: '2'

services:
  acquirer:
    image: jordimartin/mmock
    ports:
      - 8082:8082
      - 8083:8083
    environment:
      - LOG_LEVEL=INFO
      - jvmOptions=-Dmockserver.initializationJsonPath=/config/mock-acquirer-setup.json
    volumes:
      - ./config:/config
